trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'CONEXÃO ACR'
  imageRepository: 'apicalculoimc'
  containerRegistry: 'anpazdevops.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  testsDirectory: './Tests'
  collectionPostmanFile: 'CalculoIMC.postman_collection.json'
  dataPostmanTestsFile: 'data-tests-imc.json'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: BuildTestsPush
  displayName: Build, Tests and Push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build e push da imagem
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: $(dockerfilePath)
        tags: |
          $(tag)
          latest

- stage: Deployment
  displayName: Deployment no Azure App Service
  dependsOn: BuildTestsPush
  jobs:
  - job: Deployment
    displayName: Deployment
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureWebAppContainer@1
      displayName: Deployment no Azure App Service utilizando containers
      inputs:
        azureSubscription: 'AZURE SUBSCRIPTION'
        appName: 'groffecalculoimc'
        containers: '$(containerRegistry)/$(imageRepository):$(tag)'